add JavaScript accomplish
fslongjin/This-repo-has-1292-stars pull request #36
Opened 2022-09-12 15:29 UTC by BitComing

增加Javascript实现。

2022-09-12 15:32 UTC, pan93412 reviewed
用 `prettier` 跑一下代码格式化会更好一些。另外[也建议把测试代码删掉](https://github.com/fslongjin/This-repo-has-1312-stars/pull/36/files#diff-073bdc70de832f50f7dc980327160e70de441fa748259ff500877fb6da543321R34)。

2022-09-12 16:04 UTC, fslongjin requested changes

2022-09-13 03:42 UTC, BitComing commented on javascript/main.js
> +    // let regu = /This-Repo-Has-\d-Stars/;
已经做出修改

2022-09-13 04:31 UTC, BitComing commented on javascript/main.js
> +    // let regu = /This-Repo-Has-\d-Stars/;
> 这些注释建议删掉

已经做出修改

2022-09-13 05:13 UTC, fslongjin requested changes
还请麻烦你在项目根目录的readme里面，加上你这个文件夹的链接~

2022-09-13 05:32 UTC, BitComing commented
> 还请麻烦你在项目根目录的readme里面，加上你这个文件夹的链接~

在根目录readme已经添加

2022-09-13 05:34 UTC, fslongjin approved these changes

2022-09-13 05:34 UTC, merged

2022-09-13 05:35 UTC, fslongjin commented
merged. Thanks.